import type { Metadata } from "next";
import "@/styles/globals.css";
import { Poppins } from "next/font/google"
export const metadata: Metadata = {
  title: "App",
  description: "Generated by create next app",
};

const poppins = Poppins({
    weight: "300",
    subsets: ["latin"]
})

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`antialiased dark ${poppins.className}`}
      >
        {children}
      </body>
    </html>
  );
}
